### ISSUE TITLE
10) zprovoznit tu add 2x3x option .

### ISSUE THREAD

**Issue by michaldemjancuk** [michaldemjancuk/DropBotWeb#8]

**Comment by michaldemjancuk** [comment]
Jak přesně to myslíš tu 2x 3x option?

**Comment by iPko5** [comment]
Aby to bylo schopny umisťovat 2x 3x 4 x 5x někoho do dropu ty tlačítka co tm jsou . Jsi tm zatím hodil jen ty tlačítka ale nefunguji :) 

Mysli na to ať to toho člověka nedává 2x do stejného wall postu 

Ať to vždy mění obrázky na každý wall post .

Do mass dm bude vždy každý jen 1x nehledě na to v kolika wall postech bude .

Hlavně než mi to tm nahraješ nějak to zalohuj ať mužů dělat dropy ikdyz ti to bude blbnout 😂

**Comment by michaldemjancuk** [comment]
![image](https://user-images.githubusercontent.com/25272109/133461935-33a607f7-9762-47fe-a99b-6d857f49dc16.png)
Umisťování do dropu podle počtu v nastavení jde.

Okey

Dobře

Zálohy dělám furt :D

**Comment by iPko5** [comment]
![image](https://user-images.githubusercontent.com/90645474/133462475-e0f679d2-085d-497f-8321-8dc36be1d255.png) takhle to jde

**Comment by iPko5** [comment]
Any progress ?

**Comment by michaldemjancuk** [comment]
![image](https://user-images.githubusercontent.com/25272109/134023367-2cd9dc1f-13ae-447d-8fcd-349cc3e35fd3.png)

Checkni to prosím, jdu zatím na další, kdyžtak uzavřít, ať mi to tam nevisí, dík 😄 
![image](https://user-images.githubusercontent.com/25272109/134023698-1c51aef8-739f-4e0c-9186-f1d363334f02.png)

**Comment by michaldemjancuk** [comment]
Zkus, teď už by to snad mělo být naprosto v pořádku. Otestováno na mnoooha dropech...
