### ISSUE TITLE
11) preferovaný text nepoužívat jiný pokud je nějaký zaškrtnutý

### ISSUE THREAD

**Issue by michaldemjancuk** [michaldemjancuk/DropBotWeb#9]

**Comment by michaldemjancuk** [comment]
Udělám page s nastavením, kam budu postupně přidávat nastavení.

První nastavení, které bude přídáno bude

- [ ] Repeat last used text

**Comment by iPko5** [comment]
No ale to bude opakovat ten poslední já chci tlačítko u toho textu který když zaskrnu tk bude furt používat ten text pro paid drop / free drop . Takhle bych si i mohl vybrat který text a ne ten Last

**Comment by iPko5** [comment]
Nebo víš jak to udělej - udělej tm proste kolonku na free a paid . Do který budu moct přesunout ty texty který budu chtít priorizovat . Tzv by to bralo jen z první kolonky když tm něco bude . A ja když budu chtít jen 1 text tm tk si ho tm dam . Zároveň mi ta 2 kolonka muže sloužit na nepoužívane texty když budu chtít

**Comment by michaldemjancuk** [comment]
![image](https://user-images.githubusercontent.com/25272109/133138835-833ed403-9026-44c4-b4f8-4217edfecd32.png)
Mě napadlo tam udělat takhle sloupec

**Comment by michaldemjancuk** [comment]
A tam do něj dát tlačítko "use always" a vybere to u VIP, nebo FREE primárně ten vybraný k daný skupině, nebo když nebude aktivní žádný, tak ten, který byl použit nejvíc dávno.

**Comment by iPko5** [comment]
No a nebo tk a dej tomu funkce . Prirozie 
Never use 
If not prioritně use this .

**Comment by michaldemjancuk** [comment]
Use policy: Always
- Je vždy na vrchu 
![image](https://user-images.githubusercontent.com/25272109/133145109-0aee8ed5-83ec-4298-aa73-7b30730b031e.png)

Use policy: If needed

Use policy: Never use
- Je vždy dole
![image](https://user-images.githubusercontent.com/25272109/133145280-ae9f3a9d-d5a4-417e-8e03-070013ce0b10.png)

**Comment by michaldemjancuk** [comment]
Zprovozněno, pokud funguje jak má, uzavřít ticket. 
![image](https://user-images.githubusercontent.com/25272109/133146805-1e17dea6-cc91-463a-992e-efe86c55002b.png)

V opačném případě napsat :)
